

CREATE TABLE IF NOT EXISTS users(
  user_id int generated by default as identity primary key,
  login varchar(255) not null,
  email varchar(255) not null,
  user_name varchar(255),
  birthday date not null
);



CREATE TABLE IF NOT EXISTS mpa (
  mpa_id int generated by default as identity primary key,
  mpa_name varchar(255) not NULL unique
);

CREATE TABLE IF NOT EXISTS films (
  film_id int generated by default as identity primary key,
  name varchar(255) not null,
  description varchar(255) not null,
  release_date date not null,
  duration int not null,
  mpa_id int not NULL,
  FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
);


CREATE TABLE IF NOT EXISTS friends
(
  user_id int,
  friend_id int,
  foreign key (user_id) references users (user_id) on delete cascade,
  foreign key (friend_id) references users (user_id) on delete cascade,
  primary key (user_id, friend_id)
);



CREATE TABLE IF NOT EXISTS genres (
  genre_id int generated by default as identity primary key,
  genre_name varchar(255) not null unique
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id int,
  genre_id int,
  foreign key (film_id) references films (film_id) on delete cascade,
  foreign key (genre_id) references genres (genre_id) on delete cascade,
  primary key (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
 user_id int,
 film_id int,
 foreign key (film_id) references films (film_id) on delete cascade,
 foreign key (user_id) references users (user_id) on delete cascade,
 primary key (film_id, user_id)
);


